{
 "title": "Dash1",
 "description": "CPU, MEM and NETWORK IN/OUT",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "memory usage per container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name!=\"POD\",container_name!=\"\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network IN/OUT per container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"default\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"default\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "INGRESS active connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "nginx_ingress_nginx_connections_active{app=\"nginx-ingress\",job=\"kubernetes-pods\",kubernetes_namespace=\"nginx-ingress\"}"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kubelet_running_pod_count{beta_kubernetes_io_arch=\"amd64\",beta_kubernetes_io_os=\"linux\",instance=\"kubernetes1\",job=\"kubernetes-nodes-kubelet\",kubernetes_io_arch=\"amd64\",kubernetes_io_hostname=\"kubernetes1\",kubernetes_io_os=\"linux\"}"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kubelet_running_container_count{beta_kubernetes_io_arch=\"amd64\",beta_kubernetes_io_os=\"linux\",instance=\"kubernetes1\",job=\"kubernetes-nodes-kubelet\",kubernetes_io_arch=\"amd64\",kubernetes_io_hostname=\"kubernetes1\",kubernetes_io_os=\"linux\"}"
    }
   ]
  },
  {
   "title": "http://hello.sysadm.kz",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://hello.sysadm.kz\",job=\"Webservers\"}"
    }
   ]
  },
  {
   "title": "nginx ingress",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_ingress_nginx_up{app=\"nginx-ingress\",job=\"kubernetes-pods\",kubernetes_namespace=\"nginx-ingress\"}"
    }
   ]
  },
  {
   "title": "CPU Node usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage per container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name!=\"\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{addonmanager_kubernetes_io_mode=\"Reconcile\",instance=\"10.132.0.2:9100\",job=\"kubernetes-service-endpoints\",kubernetes_io_cluster_service=\"true\",kubernetes_io_name=\"NodeExporter\",kubernetes_name=\"node-exporter\",kubernetes_namespace=\"kube-system\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_MemTotal_bytes{addonmanager_kubernetes_io_mode=\"Reconcile\",instance=\"10.132.0.2:9100\",job=\"kubernetes-service-endpoints\",kubernetes_io_cluster_service=\"true\",kubernetes_io_name=\"NodeExporter\",kubernetes_name=\"node-exporter\",kubernetes_namespace=\"kube-system\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemFree_bytes{addonmanager_kubernetes_io_mode=\"Reconcile\",instance=\"10.132.0.2:9100\",job=\"kubernetes-service-endpoints\",kubernetes_io_cluster_service=\"true\",kubernetes_io_name=\"NodeExporter\",kubernetes_name=\"node-exporter\",kubernetes_namespace=\"kube-system\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job='kubernetes-service-endpoints',instance='10.132.0.2:9100'} - node_memory_MemFree_bytes{job='kubernetes-service-endpoints',instance='10.132.0.2:9100'} - node_memory_Buffers_bytes{job='kubernetes-service-endpoints',instance='10.132.0.2:9100'} - node_memory_Cached_bytes{job='kubernetes-service-endpoints',instance='10.132.0.2:9100'}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}