{
 "title": "Dash",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "memory usage per container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name!=\"POD\",container_name!=\"\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network IN/OUT per container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"default\"}[5m])) by (name)",
     "legendFormat": "IN - {{name}}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"default\"}[5m])) by (name)",
     "legendFormat": "OUT - {{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name!=\"\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "kubelet_running_container_count{beta_kubernetes_io_arch=\"amd64\",beta_kubernetes_io_os=\"linux\",instance=\"minikube\",job=\"kubernetes-nodes-kubelet\",kubernetes_io_arch=\"amd64\",kubernetes_io_hostname=\"minikube\",kubernetes_io_os=\"linux\"}"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kubelet_running_pod_count{beta_kubernetes_io_arch=\"amd64\",beta_kubernetes_io_os=\"linux\",instance=\"minikube\",job=\"kubernetes-nodes-kubelet\",kubernetes_io_arch=\"amd64\",kubernetes_io_hostname=\"minikube\",kubernetes_io_os=\"linux\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ]
  }
 ]
}