####Deploying Prometheus without PersistantVolume
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: blackbox-server
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox-server
    spec:
      containers:
        - name: blackbox
          image: prom/blackbox-exporter:v0.14.0
#          args:
#            - "--config.file=/etc/prometheus/prometheus.yml"
#            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9115
          volumeMounts:
            - name: blackbox-pv-storage   ###### STORAGE ---->>
              mountPath: /etc/blackbox_exporter/
      volumes:
        - name: blackbox-pv-storage #### <<---- STORAGE
          persistentVolumeClaim:
           claimName: blackbox-pv-claim ## CLAIM


---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-service
  namespace: default
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
      prometheus.io/probe:  'true'
spec:
  selector:
    app: blackbox-server
  type: NodePort
  ports:
    - port: 9115
      protocol: TCP
      targetPort: 9115
      nodePort: 30002
